name: freebsd

on: workflow_dispatch

jobs:
  freebsd-30:
    runs-on: ubuntu-latest

    steps:
    - uses: cross-platform-actions/action@v0.30.0
      with:
        operating_system: freebsd
        version: '13.2'
        shell: sh
        run: |
          echo "HOST: $HOST"
          hostname

  freebsd-31:
    runs-on: ubuntu-latest

    steps:
    - uses: cross-platform-actions/action@v0.31.0
      with:
        operating_system: freebsd
        version: '13.2'
        shell: sh
        run: |
          echo "HOST: $HOST"
          hostname

  freebsd-32:
    runs-on: ubuntu-latest

    steps:
    - uses: cross-platform-actions/action@v0.32.0
      with:
        operating_system: freebsd
        version: '13.2'
        shell: sh
        run: |
          echo "HOST: $HOST"
          hostname
