name: homebrew_linux_arm64

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-22.04-arm
    container:
      image: ghcr.io/homebrew/ubuntu22.04:main
      options: --user root

    steps:
    - name: Build
      run: |
        cat << EOF > prg.c
        #include <stdio.h>
        int main() {
          printf("Testing...\n");
          return 0;
        }
        EOF
        cat prg.c
        gcc --version
        gcc prg.c -o prg
        ls -l
        ./prg
