name: homebrew_linux_arm64

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-22.04-arm
    container:
      image: ghcr.io/homebrew/ubuntu22.04:main
      options: --user root

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        repository: liquidaty/zsv

    - name: Build
      run: |
        ./configure --prefix=$PWD/build
        make install
