name: ubuntu_slim

on: workflow_dispatch

jobs:
  ci: &base
    runs-on: ubuntu-slim

    steps:
    - name: Test
      run: echo 'Test'
    
    - name: Installed software
      run: apt list --installed

  ci-1: *base
